### ISSUE TITLE
`href` is not the actual `link`, it does not take parent pages into consideration

### ISSUE THREAD

**Issue by laurenskling** [shawnhooper/wpml-rest-api#10]
I've got pages with a parent page, which makes the `link`: `http://example.com/en/parent/my-page`

This plugin gives me the href `http://example.com/en/my-page` which is incorrect.

**Comment by shawnhooper** [comment]
@laurenskling There was another patch provided that fixed this issue, which has now been merged into the code.  I wanted to thank you for taking the time to submit a fix though.  Cheers.
