### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by szepeviktor** [shawnhooper/wpml-rest-api#15]
`function wpmlrestapi_calculate_rel_path(WP_Post $thisPost): string` needs PHP 7
But readme says `Requires at least: 4.7` which needs PHP 5.2
https://displaywp.com/wordpress-minimum-php-version/

How is it?

**Comment by shawnhooper** [comment]
@szepeviktor Good catch.  I've changed the minimum required WordPress version to 5.2 (and PHP 7.0).
