### ISSUE TITLE
nested pages still not handled correctly

### ISSUE THREAD

**Issue by wirsindplural** [shawnhooper/wpml-rest-api#18]
Hey! Thank you for this wonderful extension. I've found you fix targeting the nested pages issue – but it's still not working on my side. What do I miss? Thanks for your help!

**Comment by shawnhooper** [comment]
@wirsindplural.  I'll have a look as soon as I get a chance.  Thanks for letting me know!

**Comment by shawnhooper** [comment]
@wirsindplural I've just pushed an update (v1.1.2) for this plugin.   That should resolve the nested pages URL issue.  Could you confirm it works for you now?

**Comment by wirsindplural** [comment]
@shawnhooper Works like a charm. Thank you for your time and effort!
