### ISSUE TITLE
Bug when using a different post base

### ISSUE THREAD

**Issue by lukas-hablitzel** [shawnhooper/wpml-rest-api#22]
Hi,

first of all, thank you so much for the work you put into this, this plugin really helped me when working with WP in a headless setup.

Unfortunately there is one issue, when the permalink structure is set to something other than %postname% (in my case news/%postname%). In that case the link returned by the plugin is incorrect (as if the setting was still %postname%).

**Comment by shawnhooper** [comment]
Hey @lukas-hablitzel  - Thanks for the bug report. and kind words.  I'll try to get that fixed up this week.

**Comment by shawnhooper** [comment]
@lukas-hablitzel I've just released a new update to the plugin that should resolve this for you.  Note there are several other PHP updates included as well, just to modernize the code (it had been a bit!) 

If you have any problems with the new version, let me know.
