### ISSUE TITLE
Plugin doesn't work on PHP 7.1.9

### ISSUE THREAD

**Issue by riatabduramani** [shawnhooper/wpml-rest-api#5]
Hi Shawn,

Thank you for the great plugin. I have used before your plugin, but now I moved to newer PHP version, and I'm trying to figure out the problem why doesn't show the languages (wpml) on the json output.
Can you help me to figure out the problem I'm facing right now.

best regards
Riat

**Comment by shawnhooper** [comment]
Hi @riatabduramani.  Thanks for reporting this.  I'm just getting caught up on a few things after being away at WordCamp US, but I'll try testing out the plugin with PHP 7.1.9 as soon as I can and see if I can't help you get it working.

**Comment by shawnhooper** [comment]
@riatabduramani My apologies for never getting back to you about this issue.  Seems I forgot about this plugin for a bit.  I've tested it with PHP 7.4 and it's working OK.
